api/urls.py
from django.urls import path, include
from tastypie.api import Api

from api.models import PostResource, CategoryResource, CommentResource

api = Api(api_name='v1')
api.register(PostResource())
api.register(CategoryResource())
api.register(CommentResource())

urlpatterns = [
    path('', include(api.urls), name='index'),
]
"""
URL patterns for the API endpoints.

This module defines URL patterns for the API endpoints using Tastypie resources. It creates
a Tastypie API instance, registers resource classes, and includes the API's URLs in the main
urlpatterns.

URL Patterns:
- '': API endpoints provided by Tastypie resources.
"""

base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('__debug__/', include('debug_toolbar.urls')),  # DjDT panel
    path('api/', include('api.urls')),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<category>/', views.category, name='category'),
]
"""
URL patterns for the 'blog' app.

This module defines URL patterns for the views in the 'blog' app.

URL Patterns:
- '': index - The main index page.
- '<int:pk>/': detail - The detail page for a specific post.
- '<category>/': category - The category page for posts within a specific category.
"""

blog/models.py
from django.db import models


class Category(models.Model):
    """
    Model representing a category for posts.

    This model defines a category's name and creation timestamp.

    Fields:
    - name: CharField representing the category's name.
    - created_on: DateTimeField representing the creation timestamp.

    Methods:
    - __str__: Returns the category's name as the string representation.
    """

    name = models.CharField(max_length=20)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Returns the string representation of the category.
        """
        return self.name


class Post(models.Model):
    """
    Model representing a blog post.

    This model defines a post's title, body, creation timestamp, modification timestamp,
    and its associated categories.

    Fields:
    - title: CharField representing the post's title.
    - body: TextField representing the post's content.
    - created_on: DateTimeField representing the creation timestamp.
    - last_modified: DateTimeField representing the last modification timestamp.
    - categories: ManyToManyField relating the post to categories.

    Methods:
    - __str__: Returns the post's title as the string representation.
    """

    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField('Category', related_name='posts')

    def __str__(self):
        """
        Returns the string representation of the post.
        """
        return self.title


class Comment(models.Model):
    """
    Model representing a comment on a post.

    This model defines a comment's author, body, creation timestamp, and its associated post.

    Fields:
    - author: CharField representing the comment author's name.
    - body: TextField representing the comment content.
    - created_on: DateTimeField representing the creation timestamp.
    - post: ForeignKey relating the comment to a post.

    Methods:
    - __str__: Returns the string representation of the comment.
    """

    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        """
        Returns the string representation of the comment.
        """
        return f'{self.author} {self.created_on}'

blog/forms.py
from django import forms


class CommentForm(forms.Form):
    """
    A form for submitting comments.

    This form defines fields for author name and comment body. It provides placeholders and
    CSS classes for styling.

    Fields:
    - author: CharField for the author's name.
    - body: CharField for the comment body.

    Attributes:
    - author: TextInput with custom CSS classes and a placeholder for the author's name.
    - body: Textarea with custom CSS classes and a placeholder for the comment text.
    """

    author = forms.CharField(
        label="Author",
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Your Name"
        })
    )

    body = forms.CharField(
        label='Body',
        widget=forms.Textarea(attrs={
            "class": "form-control",
            "placeholder": "Leave a comment!"
        })
    )

blog/views.py
from django.shortcuts import render, get_object_or_404

from .forms import CommentForm
from .models import Post, Comment


def index(request):
    """
    View function for the index page.

    This view retrieves all posts, orders them by creation timestamp, and renders the
    'blog/index.html' template.

    Parameters:
    - request: The HTTP request object.

    Returns:
    - Rendered HTML response for the index page.
    """
    posts = Post.objects.all().order_by('-created_on')
    context = {
        'posts': posts,
    }
    return render(request, 'blog/index.html', context)


def category(request, category):
    """
    View function for displaying posts within a specific category.

    This view filters posts based on the provided category name, orders them by creation
    timestamp, and renders the 'blog/category.html' template.

    Parameters:
    - request: The HTTP request object.
    - category: The name of the category.

    Returns:
    - Rendered HTML response for the category page.
    """
    posts = Post.objects.filter(
        categories__name__contains=category
    ).order_by(
        '-created_on'
    )
    context = {
        'category': category,
        'posts': posts
    }
    return render(request, 'blog/category.html', context)


def detail(request, pk):
    """
    View function for displaying post details and handling comments.

    This view retrieves a specific post using its primary key, handles comment submissions,
    and renders the 'blog/detail.html' template.

    Parameters:
    - request: The HTTP request object.
    - pk: The primary key of the post.

    Returns:
    - Rendered HTML response for the post detail page.
    """
    post = get_object_or_404(Post, pk=pk)

    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data['author'],
                body=form.cleaned_data['body'],
                post=post
            )
            comment.save()

    comments = Comment.objects.filter(post=post)
    context = {
        'post': post,
        'comments': comments,
        'form': form,
    }
    return render(request, 'blog/detail.html', context)

templates/blog/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends "base.html" %}
    {% block page_content %}
    <div class="col-md-8 offset-md-1">
        <h1>{{ category | title }}</h1>
        <hr>
        {% for post in posts %}
            <h2><a href="{% url 'blog:detail' post.pk%}">{{ post.title }}</a></h2>
            <small>
                {{ post.created_on.date }} |&nbsp;
                Categories:&nbsp;
                {% for category in post.categories.all %}
                <a href="{% url 'blog:category' category.name %}">
                    {{ category.name }}
                </a>&nbsp;
                {% endfor %}
            </small>
            <p>{{ post.body | slice:":400" }}...</p>
        {% endfor %}
    </div>
    {% endblock %}
</body>
</html>

templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends "base.html" %}
    {% block page_content %}
    <div class="col-md-8 offset-md-1">
        <h1>{{ post.title }}</h1>
        <small>
            {{ post.created_on.date }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
            <a href="{% url 'blog:category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
        </small>
        <p>{{ post.body | linebreaks }}</p>
        <h3>Leave a comment:</h3>
        <form action="/{{ post.pk }}/" method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form.author }}
            </div>
            <div class="form-group">
                {{ form.body }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <h3>Comments:</h3>
        {% for comment in comments %}
        <p>
            On {{comment.created_on.date }}&nbsp;
            <b>{{ comment.author }}</b> wrote:
        </p>
        <p>{{ comment.body }}</p>
        <hr>
        {% endfor %}
    </div>
    {% endblock %}
</body>
</html>

templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% extends "base.html" %}
    {% block page_content %}
    <div class="col-md-8 offset-md-1">
        <h1>Blog Index</h1>
        <hr>
        {% for post in posts %}
        <h2><a href="{% url 'blog:detail' post.pk%}">{{ post.title }}</a></h2>
        <small>
            {{ post.created_on.date }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
            <a href="{% url 'blog:category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
        </small>
        <p>{{ post.body | slice:":400" }}...</p>
        {% endfor %}
    </div>
    {% endblock %}
</body>
</html>