api/urls.py
from django.urls import path, include
from tastypie.api import Api

from api.models import PostResource, CategoryResource, CommentResource

api = Api(api_name='v1')
api.register(PostResource())
api.register(CategoryResource())
api.register(CommentResource())

urlpatterns = [
    path('', include(api.urls), name='index'),
]
"""
URL patterns for the API endpoints.

This module defines URL patterns for the API endpoints using Tastypie resources. It creates
a Tastypie API instance, registers resource classes, and includes the API's URLs in the main
urlpatterns.

URL Patterns:
- '': API endpoints provided by Tastypie resources.
"""

base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('__debug__/', include('debug_toolbar.urls')),  # DjDT panel
    path('api/', include('api.urls')),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<category>/', views.category, name='category'),
]
"""
URL patterns for the 'blog' app.

This module defines URL patterns for the views in the 'blog' app.

URL Patterns:
- '': index - The main index page.
- '<int:pk>/': detail - The detail page for a specific post.
- '<category>/': category - The category page for posts within a specific category.
"""

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% load static %}
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'blog:index' %}">Blog App</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" target = "_blank" href="/admin/">Admin</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" target = "_blank" href="/api/v1/">API</a>
                </li>
                <!-- could be more links -->
              </ul>
            </div>
        </div>

    </nav>

    <div class="container">
        {% block page_content %}{% endblock %}
    </div>
</body>
</html>